# Generated by Django 5.1.6 on 2025-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/identity/'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='store_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
